### ISSUE TITLE
Typo collection 

### ISSUE THREAD

**Issue by stellalong** [rstudio/rmarkdown-book#103]
You may also suggest new topics to us. Thanks!

In chapter 3.2, 
> There is also a Restart R and Run All Chunks item in the Run menu on the editor toolbar, which gives you a fresh R session prior to running all the chunks. 

It's now in the Session menu, not the Run menu😂

**Comment by yihui** [comment]
Thanks! I just deleted this paragraph. The menu item seems to have been removed from the `Run` menu since a certain version of RStudio.
