### ISSUE TITLE
Description of `include_graphics`

### ISSUE THREAD

**Issue by mikey-harper** [rstudio/rmarkdown-book#2]
From what I can see, images are discussed briefly in [Section 2.4.1](https://bookdown.org/yihui/rmarkdown/markdown-syntax.html#)  using the syntax `[alt text or image title](path/to/image)` . However, I feel the `include_graphics()` method is more stable, as is already explained in [bookdown book](https://bookdown.org/yihui/bookdown/figures.html).

I can't see any reference to this anywhere in the book,  but wanted to ask where best to insert it before making a pull request? I would suggest that is shown quite early on, probably in the `Basics` chapter, but I cannot see a natural place for it to fit in currently.

**Comment by yihui** [comment]
Yes, we need to talk about both graphics and tables. I think two subsections can be added to Section 2.5: https://bookdown.org/yihui/rmarkdown/r-code.html, which can be summaries of Section 2.4 and 2.5 of the bookdown book.

- https://bookdown.org/yihui/bookdown/figures.html
- https://bookdown.org/yihui/bookdown/tables.html

**Comment by mikey-harper** [comment]
I will make a pull request with these changes over the coming few days.

**Comment by mikey-harper** [comment]
#8 has addressed these.
