### ISSUE TITLE
Switch chapter order: blogdown and bookdown

### ISSUE THREAD

**Issue by mikey-harper** [rstudio/rmarkdown-book#3]
As **blogdown** is based on the **bookdown** package, would it make more sense to first have the chapter on **bookdown** before **blogdown**?

**Comment by yihui** [comment]
It probably doesn't matter. My reason for the current order is that I think there will be way more people who build websites than those who write books, so I want readers to see how to build websites first. Blogdown is based on bookdown only in the sense of `blogdown::html_page` (i.e. the extended Markdown syntax), which may not be a big deal for most users, if they don't care about advanced features like figure/table captions, cross-references, theorems, and so on.

**Comment by mikey-harper** [comment]
Okay, that makes sense! The order of two chapters probably ultimately won't change thing.

Although from my experience, people I know tend to use bookdown more. This might reflect that I work with a lot of academics who tend to produce longer reports (and that I have been ranting to them about the benefits of bookdown for the past year).
