### ISSUE TITLE
4.1.5 Customizing logos added to each slide | R Markdown ioslides

### ISSUE THREAD

**Issue by jananiravi** [rstudio/rmarkdown-book#31]
Hi,
I'd like to adjust use the `css` customizations suggested in the section 4.1.5 on 'Adding a logo' to increase the logo size in all my slides, but I'm not sure which file I should edit. I only see the `defaults.css` file (under ...files>ioslides...>theme>css) that's created after I knit my current `.Rmd` presentation. Where can I add these customizations so that the bottom left logos in each slide appear a bit larger? And how can I make sure that this works robustly? Thanks!

**Comment by mikey-harper** [comment]
As stated in Section 4.1.3.5, you will need to add your own CSS to ioslides using the `css` option. You can then include any custom CSS options in this file.
