### ISSUE TITLE
Inconsistency in 2.6": fig.align

### ISSUE THREAD

**Issue by KyleHaynes** [rstudio/rmarkdown-book#38]
Should **center** include quotes?

> fig.align: The alignment of plots. It can be 'left', center, or 'right'.

**Comment by yihui** [comment]
Oops! Fixed. Thanks for letting me know!

BTW, next time if you spot any typos, you could hit the Edit button on the toolbar to propose a fix: https://bookdown.org/yihui/rmarkdown/r-code.html

**Comment by KyleHaynes** [comment]
Will do! Didn't know you could do that.

This is an amazing reference guide - thanks so much for it 😄
