### ISSUE TITLE
bold text not works properly

### ISSUE THREAD

**Issue by dongzhuoer** [rstudio/rmarkdown-book#44]
![image](https://user-images.githubusercontent.com/15871952/49566480-b3e5e000-f965-11e8-98ee-be722bb3bfe8.png)

**Comment by dongzhuoer** [comment]
```md
Package names are in bold text (e.g., **rmarkdown**),
```

**Comment by dongzhuoer** [comment]
Using the develeoper tool in Chrome, I found there might be some conflicts in the CSS file

![image](https://user-images.githubusercontent.com/15871952/49566557-ff988980-f965-11e8-9d76-c5d43002c24b.png)

**Comment by yihui** [comment]
It looks good to me on macOS with the latest version of Chrome:

[![image](https://user-images.githubusercontent.com/163582/49594665-027e8480-f93c-11e8-87f4-39514366abc0.png)](https://bookdown.org/yihui/rmarkdown/software-info.html)

Might be an issue on Windows. Anyway, I have applied the fix https://github.com/rstudio/bookdown/pull/627. Thanks!

**Comment by yihui** [comment]
You don't need the next release of **bookdown**. It is a CSS issue that you can and should fix by yourself: f907235.

**Comment by dongzhuoer** [comment]
I see. Yeah, it has been fixed now.
