### ISSUE TITLE
Failed local build

### ISSUE THREAD

**Issue by asimumba** [rstudio/rmarkdown-book#5]
This maybe a bother, I don't know? But I'm trying to follow the development of the book locally on my computer. Though I keep getting this error despite installing the missing packages: 

> Quitting from lines 635-893 (rmarkdown.Rmd) 
Error: 'file_string' is not an exported object from 'namespace:xfun'
Execution halted
Error: Failed to compile the book to bookdown::pdf_book
In addition: Warning message:
running command '"C:/PROGRA~1/R/R-34~1.4/bin/x64/Rscript" -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book', quiet = FALSE)"' had status 1 
Execution halted
Error in render_book_script(output_format, envir, quiet) : 
  Error 1 attempting to render book
Calls: <Anonymous> -> <Anonymous> -> in_dir -> render_book_script
In addition: Warning message:
running command '"C:/PROGRA~1/R/R-34~1.4/bin/x64/Rscript" _render.R "bookdown::pdf_book"' had status 1 
Execution halted

Exited with status 1.

**Comment by yihui** [comment]
```r
devtools::install_github('yihui/xfun')
```

**Comment by asimumba** [comment]
Thanks. Up and running.

**Comment by asimumba** [comment]
Thank you. You can trust me with nuclear codes. 💯
