### ISSUE TITLE
Typo in Chapter 2

### ISSUE THREAD

**Issue by RaymondBalise** [rstudio/rmarkdown-book#61]
I think the three backticks on line 39 of:
https://github.com/rstudio/rmarkdown-book/blob/master/02-basics.Rmd
should not be there.  The closing back backticks for the code block are already on line 36.

**Comment by yihui** [comment]
Thanks, but that is not a typo. Note the four backticks below. This is a full fenced code block:

https://github.com/rstudio/rmarkdown-book/blob/9acc797f45a93547291bb53bbfdf650169865504/02-basics.Rmd#L26-L40

More on four backticks:

- https://yihui.org/en/2018/11/hard-markdown/
- https://yihui.org/en/2018/05/github-issue-format/
- https://yihui.org/en/2017/05/four-backticks-github/

**Comment by RaymondBalise** [comment]
I am really confident that the back ticks on line 39 do not belong there.  Take a look at the end of the second code chunk on: https://bookdown.org/yihui/rmarkdown/basics.html and you will see three backticks that seem to serve no purpose.   If they belong can you please explain why the three backticks are on line 39?

**Comment by yihui** [comment]
Oh you are right. I just removed these backticks. Thank you!
