### ISSUE TITLE
Custom macros?  Not a widget, but a macro

### ISSUE THREAD

**Issue by MonteShaffer** [rstudio/rmarkdown-book#76]
If I wanted to create a new macro, similar to the $ or $$ macro for mathematics, how would I do that?

In that same line, if I wanted to create a parser that would take LATEX code in its native format and "translate" it so it could render as HTML without forcing the LATEX code to match the very limited Rmd syntax.

How do I underline in Rmd exactly?  How do I embed nested HTML?  It is very limited, so there needs to be some macro options such as "ignore".  Include as HTML but ignore in terms of processing.

For example,

<DIV border=...><IMG SRC=...></DIV

That is nested HTML and breaks.

How can I include HTML blocks inline from an external source.  Not in YAML as header/footer, but inline "similar to latex input syntax".

It seems like you are trying to build a templating language without all the necessary ingredients.  If I want to hack on it, how do I do that?

**Comment by cderv** [comment]
Hi @MonteShaffer, 

Thank you for your question. The Github Repo is not the best place to discuss How-To on the package. You can asked for specific question in https://community.rstudio.com for example. (BTW you image link is broken)

Anyway, as you are asking here, I suppose you have already read the book : [R Markdown - The Definitive Guide](https://bookdown.org/yihui/rmarkdown/). 

There is a new one with more advanced recipes that you can find useful regarding customization; [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/). 

In those documents, you will find what is under the hood, especially [here](https://bookdown.org/yihui/rmarkdown-cookbook/conceptual-overview.html). 

About R markdown, this is a format to provide an authoring framework for Datascience that was designed for reproducibiliy by allowing to mix code and their results with some narrative to produce a wide variety of formats. 
By templating language, what do you have in mind ? 

Here are some hints regarding your different questions. Let just remind that **rmarkdown**, is using **knitr** to evaluate the code and produce a document mixing code results and narrative to be converted to an ouptut format by **pandoc** tools. If you want advanced customisation, or even building extensions, you'll need to look into those pieces. 

> If I wanted to create a new macro, similar to the $ or $$ macro for mathematics, how would I do that?

Maths is processed by Pandoc : https://pandoc.org/MANUAL.html#math. By default, Rmarkdown use Mathjax to deal with Math and HTML output. The `$` and `$$` are Pandoc syntax for Tex Math, also [recognize by Mathjax (](http://docs.mathjax.org/en/latest/basic/mathematics.html)

> In that same line, if I wanted to create a parser that would take LATEX code in its native format and "translate" it so it could render as HTML without forcing the LATEX code to match the very limited Rmd syntax.

I believe you need to look at how Pandoc is working to convert document. There are possibilities of customization using Lua filter for example if you don't find what you want with conversion capabilites of Pandoc. R markdown is design to convert from markdown to other output. If you want to convert from Latex to HTML, maybe Pandoc will be enough. 

> to match the very limited Rmd syntax.

I am not sure to correctly understand this. Rmd syntax is as large as Markdown syntax can be + what Pandoc can handle. And it is already a pretty wide syntax allowing a vast number of feature. You'll need to be more precise if you have ideas on what we can improve.

> How do I underline in Rmd exactly?

AFAIK this is not a supported syntax in Markdown markup. You can achieve underline text inserting a syntax based on your output (HTML, PDF, ...)

> How do I embed nested HTML? 

What is nested HTML ? You can embeded HTML in Rmd document already. Htmlwidgets in R are HTML and can be embeded, but raw html can be embeded too. Have you tried already ? 

> so there needs to be some macro options such as "ignore". Include as HTML but ignore in terms of processing.

Sorry but I did not understand this ?

> How can I include HTML blocks inline from an external source. Not in YAML as header/footer, but inline "similar to latex input syntax".

You can easily to that with a code chunk to import your HTML file inside the document body. Headers and Footers are special insertation to be placed correctly in Pandoc's template and so they are supported as a Pandoc's variable you can pass in the YAML header, or an argument in **rmarkdown** output format.

> If I want to hack on it, how do I do that?

You can do a lot of things using R code coupled with using **knitr** and **pandoc** customization features. There are some examples format out there of what you can do to create you own customized format to extend rmarkdown. 

I close this for sanity as there is no issue with the book related to this ticket, but happy to continue the discussion.

**Comment by MonteShaffer** [comment]
Thanks.  I had read your book on "widgets" and fundamentally wanted to understand how to add "macros" as it seems this entire interface is a templating system.

Thank you for the patience with my stream-of-conscious questions.  Your book was well written, and I was focusing on "what's missing" ... not necessarily in your book, but with the current form of the templating system.

Re-syntaxing Latex to work inside of Rmd is not necessary if there was a parsing macro allowed that would convert Latex to HTML, see Latex.js for example.  https://latex.js.org/

The odd rules of "templating" makes me wonder if its intentionally obfuscating.  The classic strategy of "owning the platform" at the cost of limiting hooks and abandoning historic syntax.

**Comment by cderv** [comment]
> wanted to understand how to add "macros" as it seems this entire interface is a templating system.

I am not sure to well understand what is behind your use of the word "Macros". I would like to understand better so that I am sure to talk about the right think. Can you give example or describe what you mean ? 

By Widgets, you are talking about **htmlwidget** ? HTML component added in document. Right ? 

> I was focusing on "what's missing" 

That is very interesting feedback ! I welcome your idea. 

> Re-syntaxing Latex to work inside of Rmd is not necessary if there was a parsing macro allowed that would convert Latex to HTML, see Latex.js for example. https://latex.js.org/

Thanks for sharing ! I did not know this one: that is a great tool ! 

Regarding conversion between language, **rmarkdown** is enpower by **Pandoc**. **rmarkdown** will contains text and chunk of code unevaluated, it will run **knitr** to evaluate the code and produce a `.md` document containing text, code and results, all in markdown file with a syntax that **Pandoc** can understand, so that it is able to convert to different format from the same file. 
Latex to HTML conversion is possible with **Pandoc**. Basically, it is made of Readers, that produces a AST of the document for Writers to transform into the expected language. 

You can add what I think you call "Macros" using some extension mechanism in Pandoc using [lua filters](https://pandoc.org/lua-filters.html). This allow to modify the AST to modify the document after parsing and before writing. We use this to add some feature in **rmarkdown** like pagebreak using `\newpage` syntax in Rmd to work with all types of documents (PDF, HTML, DOCX, ODT, EPUB, ...).
