### ISSUE TITLE
New slide in Xaringan

### ISSUE THREAD

**Issue by bjornerstedt** [rstudio/rmarkdown-book#81]
Section 7.3.1 begins with

Every new slide is created under a horizontal rule (---). 

In order to get a new slide, the dashes have to be followed by a new line. It took me a bit of googling to discover this. The text should be modified to describe actual behavior. For example add:

Note that the dashes have to be followed by a new line.

**Comment by cderv** [comment]
In fact I may have added this two quickly. You can have now empty line between dashes. 

````md
---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, PBC"
date: "2020-12-14"
output:
  xaringan::moon_reader: default
---

# Slide 1
---
# Slide 2
---
# Slide 3
````

You must have encountered another issue.

**Comment by bjornerstedt** [comment]
Yes, I was referrring to adding a space after the dashes on the same line "--- ". I get a horizontal rule rather than a new slide. This behavior might be intentional, but I have not seen it clearly documented. (In addition it is rather unusual for trailing whitespaces to have syntactic meaning.)

**Comment by cderv** [comment]
Oh I see - I misunderstood it. Thanks for the precision.

**Comment by cderv** [comment]
Related to https://github.com/yihui/xaringan/issues/151 and https://github.com/yihui/xaringan/issues/208

> In addition it is rather unusual for trailing whitespaces to have syntactic meaning.

This is due to remark.js and how it handles markdown.
