### ISSUE TITLE
Automatic deployment of the book

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown-book#85]
@yihui should I also apply the same deployment process as the other books for this one ? 

Would that be ok ?

**Comment by yihui** [comment]
Sure!

**Comment by yihui** [comment]
Just want to make sure, since you are the admin of both this Github repo and bookdown.org, I guess you won't need me to set up anything for you, right?

**Comment by cderv** [comment]
Yes I think this will be ok. I can setup the necessary settings. Thanks !
